apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  labels:
    app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
        - name: node-web-app
          image: 446093446159.dkr.ecr.us-east-1.amazonaws.com/nodejs-cicd
          ports:
            - containerPort: 8080
